spring:
  application:
    name: Patient Api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true

  datasource:
    url: jdbc:mysql://patientdb:3306/patient_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    username: mysql
    password: rootpw

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG